# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

env:
  global:
    - CODECOV_TOKEN="53f8a90d-30c3-44ac-9c06-e36732c89a8a"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту yanin.r.a@mail.ru если сборка упала
notifications:
  email:
    recipients:
      - yanin.r.a@mail.ru
    on_success: never # default: change
    on_failure: always # default: always